/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lib;

import org.junit.jupiter.api.Test;
import lib.exception.NotNumberException;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void checkIfNumberIsPositive() {
        String number = "123";
        assertTrue(StringUtils.isPositiveNumber(number));
    }

    @Test
    public void checkIfNumberIsNegative() {
        String number = "-123";
        assertFalse(StringUtils.isPositiveNumber(number));
    }

    @Test()
    public void checkNotNumber() {
        String number = "-1ee23";
        assertThrows(NotNumberException.class, () -> StringUtils.isPositiveNumber(number));
    }
}
